Hw04
Konstantin-Kolom/nodejs-homework-rest-api pull request #3
Opened 2021-12-07 14:58 UTC by Konstantin-Kolom

2021-12-07 20:34 UTC, KirillKulakow commented on controllers/contacts/addContact.js
> +    message: 'contancts uploaded',
что то тут не то

2021-12-07 20:35 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
> +    message: 'сontant uploaded',
Не пойму что ты тут имеешь ввиду content или contact?

2021-12-07 20:42 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
>    const contact = await Contact.findById(contactId);
добавить поиск не только по ид но и по собственнику

2021-12-07 20:43 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit;
сделать валидацию входящих данных page limit

2021-12-07 20:44 UTC, KirillKulakow commented on controllers/contacts/removeContact.js
>    const contact = await Contact.findByIdAndRemove(contactId);
сделать поиск и по ид собственника чтобы мог удалить только собственник

2021-12-07 20:45 UTC, KirillKulakow commented on controllers/contacts/updateContact.js
>    const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true });
добавить ид собственника

2021-12-07 20:46 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
>    const contact = await Contact.findByIdAndUpdate(contactId, { favorite }, { new: true });
добавить ид собственника

2021-12-07 20:47 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  console.log(userId);
удалить

2021-12-07 20:47 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  console.log(req);
удалить

2021-12-07 20:49 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  const { userId } = req.params;
это странно
точно из параметров ид брать нужно?

2021-12-07 20:51 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById));
здесь миддлвара аутентификации не нужна?

2021-12-07 20:51 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.delete('/:contactId', ctrlWrapper(ctrl.removeContact));
тот же вопрос

2021-12-07 20:52 UTC, KirillKulakow commented on routes/api/users.js
> +router.patch('/:userId', validation(joiSubscriptionSchema), ctrlWrapper(ctrl.updateSubscription));
всмысле? любой юзер может обновить статус себе или другому юзеру?

2021-12-07 20:52 UTC, KirillKulakow requested changes
Need fix

2021-12-08 17:31 UTC, Konstantin-Kolom commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById));
Не пойму почему не нужна? Открывается список по токену пользователя и только его контакты...?

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/addContact.js
> +    message: 'contancts uploaded',
поправил

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/getContactById.js
> +    message: 'сontant uploaded',
поправил

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/getContactById.js
>    const contact = await Contact.findById(contactId);
поправил

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit;
сдалал

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/removeContact.js
>    const contact = await Contact.findByIdAndRemove(contactId);
поправил

2021-12-08 17:32 UTC, Konstantin-Kolom commented on controllers/contacts/updateContact.js
>    const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true });
поправил

2021-12-08 17:33 UTC, Konstantin-Kolom commented on controllers/contacts/updateFavorite.js
>    const contact = await Contact.findByIdAndUpdate(contactId, { favorite }, { new: true });
поправил

2021-12-08 17:33 UTC, Konstantin-Kolom commented on controllers/users/updateSubscription.js
> +  console.log(userId);
поправил

2021-12-08 17:33 UTC, Konstantin-Kolom commented on controllers/users/updateSubscription.js
> +  console.log(req);
поправил

2021-12-08 17:33 UTC, Konstantin-Kolom commented on controllers/users/updateSubscription.js
> +  const { userId } = req.params;
переделал - ИД из боди беру

2021-12-08 17:35 UTC, Konstantin-Kolom commented on routes/api/contacts.js
>  router.delete('/:contactId', ctrlWrapper(ctrl.removeContact));
Добавлять может только авторизированный пользователь - по этому добавил... ?

2021-12-08 17:38 UTC, Konstantin-Kolom commented on routes/api/users.js
> +router.patch('/:userId', validation(joiSubscriptionSchema), ctrlWrapper(ctrl.updateSubscription));
Ну нет конечно)  Исправил. Но сам юзер тоже себе не может его менять, админ должен наверное)

2021-12-08 17:41 UTC, Konstantin-Kolom commented
Внес правки.

2021-12-08 19:44 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
>    const contact = await Contact.findById(contactId);
не вижу изменений

2021-12-08 19:45 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit;
проверку делать лучше до того как ты будешь выполнять какие либо математические действия

2021-12-08 19:46 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  const result = await User.findByIdAndUpdate(userId, { subscription }, { new: true });
сделай лучше так чтобы юзер мог обновить только свою подписку

2021-12-08 19:47 UTC, KirillKulakow requested changes
Need fix

2021-12-08 19:48 UTC, KirillKulakow commented on routes/api/users.js
> +router.patch('/:userId', validation(joiSubscriptionSchema), ctrlWrapper(ctrl.updateSubscription));
сделай так чтобы юзер только себе мог обновить подписку

2021-12-08 19:49 UTC, KirillKulakow commented on controllers/contacts/removeContact.js
>    const contact = await Contact.findByIdAndRemove(contactId);
нет изменений

2021-12-08 19:50 UTC, KirillKulakow commented on controllers/contacts/updateContact.js
>    const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true });
не вижу изменений

2021-12-08 22:16 UTC, Konstantin-Kolom commented on routes/api/users.js
> +router.patch('/:userId', validation(joiSubscriptionSchema), ctrlWrapper(ctrl.updateSubscription));
Я это исправил - добавил userCurrent,   router.patch(  '/:userId',  userCurrent,....

2021-12-08 22:43 UTC, Konstantin-Kolom commented on controllers/contacts/getContactById.js
>    const contact = await Contact.findById(contactId);
Добавил.

2021-12-08 22:45 UTC, Konstantin-Kolom commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit;
поправил)

2021-12-09 14:24 UTC, Konstantin-Kolom commented on controllers/contacts/removeContact.js
>    const contact = await Contact.findByIdAndRemove(contactId);
сделал

2021-12-09 14:32 UTC, Konstantin-Kolom commented on controllers/contacts/updateContact.js
>    const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true });
Сделал

2021-12-09 14:42 UTC, Konstantin-Kolom commented on controllers/users/updateSubscription.js
> +  const result = await User.findByIdAndUpdate(userId, { subscription }, { new: true });
сделал

2021-12-09 14:44 UTC, Konstantin-Kolom commented on routes/api/users.js
> +router.patch('/:userId', validation(joiSubscriptionSchema), ctrlWrapper(ctrl.updateSubscription));
Поправил

2021-12-09 14:56 UTC, Konstantin-Kolom commented
Внес правки.

2021-12-09 20:36 UTC, KirillKulakow requested changes
Need fix

2021-12-09 20:36 UTC, KirillKulakow approved these changes

2021-12-12 15:32 UTC, merged