05hw
Konstantin-Kolom/nodejs-homework-rest-api pull request #4
Opened 2021-12-18 15:49 UTC by Konstantin-Kolom

2021-12-18 20:07 UTC, KirillKulakow commented on app.js
> +app.use(express.static('publik'));
поправь название папки на public

2021-12-18 20:09 UTC, KirillKulakow commented on controllers/users/signup.js
> +const { valid } = require('joi');
зачем этот импорт?

2021-12-18 20:09 UTC, KirillKulakow commented on controllers/users/signup.js
> +  const avatarURL = gravatar.url(email);
добавить опцию протокола

2021-12-18 20:10 UTC, KirillKulakow commented on controllers/users/updateAvatars.js
> +const avatarsDir = path.join(__dirname, '../../publik/avatars');
поправить название папки

2021-12-18 20:10 UTC, KirillKulakow commented on middlewares/fnUploadAvatar.js
> +  filename: (req, file, cb) => {
было бы неплохо добавить проверку на тип файла

2021-12-18 20:12 UTC, KirillKulakow commented on controllers/index.js
> +// const avatars = require('./avatars');
почему закоментировано? или использовать или удалить

2021-12-18 20:12 UTC, KirillKulakow commented on controllers/index.js
> +  //   avatars,
так же

2021-12-18 20:12 UTC, KirillKulakow requested changes
Need fix

2021-12-19 15:24 UTC, Konstantin-Kolom commented on app.js
> +app.use(express.static('publik'));
поправил

2021-12-19 15:25 UTC, Konstantin-Kolom commented on controllers/users/signup.js
> +const { valid } = require('joi');
убрал, видимо я крутил что то) и автоматом импорт прописался

2021-12-19 15:25 UTC, Konstantin-Kolom commented on controllers/users/updateAvatars.js
> +const avatarsDir = path.join(__dirname, '../../publik/avatars');
поправил

2021-12-19 15:26 UTC, Konstantin-Kolom commented on controllers/index.js
> +// const avatars = require('./avatars');
убрал

2021-12-19 15:26 UTC, Konstantin-Kolom commented on controllers/index.js
> +  //   avatars,
убрал

2021-12-19 16:07 UTC, Konstantin-Kolom commented on middlewares/fnUploadAvatar.js
> +  filename: (req, file, cb) => {
сделал что бы только png...

2021-12-19 16:15 UTC, Konstantin-Kolom commented on controllers/users/signup.js
> +  const avatarURL = gravatar.url(email);
добавил

2021-12-19 18:25 UTC, Konstantin-Kolom commented on middlewares/fnUploadAvatar.js
> +  filename: (req, file, cb) => {
также добавил форматирование  jimp... упустил

2021-12-20 19:48 UTC, KirillKulakow approved these changes

2021-12-20 20:20 UTC, merged