Hw06 email
Konstantin-Kolom/nodejs-homework-rest-api pull request #5
Opened 2021-12-24 17:57 UTC by Konstantin-Kolom

2021-12-24 20:07 UTC, KirillKulakow commented on controllers/users/reVerifyEmail.js
> +  console.log(email);
?

2021-12-24 20:07 UTC, KirillKulakow commented on controllers/users/reVerifyEmail.js
> +  if (user.verify === true) {
почем не написать
` if(user.verify)`

2021-12-24 20:10 UTC, KirillKulakow commented on controllers/users/verifyEmail.js
> +  console.log(user);
?

2021-12-24 20:12 UTC, KirillKulakow requested changes
need fix

2021-12-24 22:31 UTC, Konstantin-Kolom commented on controllers/users/reVerifyEmail.js
> +  if (user.verify === true) {
можно. по писал наверняка... что то не сразу работало...  Поправил

2021-12-24 22:32 UTC, Konstantin-Kolom commented on controllers/users/reVerifyEmail.js
> +  console.log(email);
Консоль лог убрал.

2021-12-24 22:32 UTC, Konstantin-Kolom commented on controllers/users/verifyEmail.js
> +  console.log(user);
убрал

2021-12-26 15:15 UTC, KirillKulakow approved these changes

2021-12-29 12:09 UTC, merged